# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Menu
  description: Home Menu
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: home
    title: Menu
    sub_title: Our chef are cooking for you
    menu_items:
      - title_item: Spaghetti
        banner_item:
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
      - title_item: Spaghetti
        banner_item:
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
      - title_item: Spaghetti
        banner_item:
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
          - img_item: /images/img_food.png
            img_alt_item: Food
            background_item: "#ffffff4d"
            evaluate: 5
            icon_star: /images/star.svg
            title_item: Black pepper spaghetti
            sub_title_item: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit amet molestie eros, a molestie neque.
            icon_cart: /images/ic_cart_food.svg
            price_new: 29$
            price_old: 39$
        icon_minus: images/ic_minus.svg
        icon_plus: images/ic_plus.svg
    view_more: View more
    text_order: Your  Order 
    icon_cart: /images/ic_cart_food.svg
    icon_menu_board: /images/menu_board_hero.svg

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      label: Id Section
    
