# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Section
  description: About Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: about
    title: About us
    background: images/bg-pink.png
    alt_image: Beauty Nails
    link_video: https://www.youtube.com/embed/d_wfY6lrHxA
    cone: images/non.png
    content: Are you looking for a time of relaxation or just something new and different to pamper yourself? At Loveland Nails & Spa, you can enjoy the highest quality services from our professional technicians. Our priority is your well-being, health, and safety. We are committed to providing more than 90% of our natural products, advanced equipment, and a clean and fresh atmosphere.   
    submit: View more


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      label: Id Section 
    title:
      type: text
      label:  Title
    background:
      type: image
      label: Background 
    alt_image:
      type: text
      label:  Alt Image
    link_video:
      type: text
      label: Link Video
    title_youtube:
      type: text
      label: Title Youtube
    cone:
      type: image
      label: Image Cone 
    content:
      type: markdown
      label: Context
    submit:
      type: text
      label:  View More


    

