# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Section
  description: Contact Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: contact
    background: /images/bg-contact.png
    logo_title: /images/logo_title.png
    logo_logo_title_alt: sushi
    circle: /images/circle.svg
    circle_alt: sushi
    title: CONTACT US
    title_form: Get in touch
    input_name: Your name
    input_email: Your email address
    area_name: Enter your name
    btn_submit: Submit
    title_call: CALL US
    ic_call: /images/ic_phone.svg
    phone_number: (234) 567-8911
    title_address: Address
    ic_address: /images/ic_location.svg
    text_address: 11011 Richmond Ave, Ste 900, Houston, TX 77042
    title_follow: Follow us
    ic_facebook: /images/ic_facebook.svg
    text_facebook: FASTBOY MARKETING
    ic_youtube: /images/ic_youtube.svg
    text_youtube: Fastboy Marketing Official
    ic_instagram: /images/ic_instagram.svg
    text_instagram: fastboy.official
    ic_google: /images/google.svg
    text_google: FASTBOY MARKETING
    google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d50607.00508097254!2d-122.35682970726366!3d37.556528792240066!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808f9e60efa95545%3A0xfd8efcf42dcc1ba7!2sSan%20Mateo%2C%20California%2C%20Hoa%20K%E1%BB%B3!5e0!3m2!1svi!2s!4v1703040028360!5m2!1svi!2s



# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      label: Id Section
    background:
      type: image
      label: Background
    logo_title:
      type: image
      label: Logo Title
    logo_logo_title_alt:
      type: text
      label: Logo Title Alt
    circle:
      type: image
      label: Image Circle
    circle_alt:
      type: text
      label: Image Circle Alt
    title:
      type: text
      label: Title
    title_form:
      type: text
      label: Title Form
    input_name:
      type: text
      label: Input Name
    input_email:
      type: text
      label: Input Email
    area_name:
      type: text
      label: Area Name
    btn_submit:
      type: text
      label: Submit
    title_call:
      type: text
      label: Tile Call
    ic_call:
      type: image
      label: Icon Call
    phone_number:
      type: text
      label: Phone Number
    title_address:
      type: text
      label: Title Address
    ic_address:
      type: image
      label: Image Address
    text_address:
      type: text
      label: Text Address
    title_follow:
      type: text
      label: Title Follow
    ic_facebook:
      type: image
      label: Image Facebook
    text_facebook:
      type: text
      label: Text FaceBook
    ic_youtube:
      type: image
      label: Image Youtube
    text_youtube:
      type: text
      label: Text Youtube
    ic_instagram:
      type: image
      label: Image Instagram
    text_instagram:
      type: text
      label: Text Instagram
    ic_google:
      type: image
      label: Image Google
    text_google:
      type: text
      label: Text Google
    google_map:
      type: text
      label: Google Map

    

