# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Section
  description: Hero Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: hero
    icon_right: /images/ic_right.svg
    icon_left: /images/ic_left.svg
    title: Tasty <p/> Food is waiting </p> afor you
    sub_title:
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sit
          amet molestie eros, a molestie neque. Sed ac blandit nisi, eu mattis ex.
          Donec vitae lorem eu lectus hendrerit sollicitudin tincidunt non odio.
    visit_our_menu: Visit Our Menu
    icon_menu_board: /images/menu_board_hero.svg
    link_menu: /menu
    item_banner:
      - image_banner: /images/banner_hero.png
        image_banner_alt: Food
      - image_banner: /images/banner_hero.png
        image_banner_alt: Food
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      label: Id Section
    icon_right:
      type: image
      label: Icon Right
    icon_left:
      type: image
      label: Icon Left 
    item_banner[*].image_banner:
      type: image
      label: Image Banner
    item_banner[*].image_banner_alt:
      type: text
      label: Image Banner Alt
    title:
      type: text
      label: Item Title
    sub_title:
      type: markdown
      label: Item Sub Title
    visit_our_menu:
      type: Text
      label: Visit Our Menu
    icon_menu_board:
      type: image
      label: Icon Menu Board
    link_menu:
      type: text
      label: Link Menu




