# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Interior Section
  description: Interior Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: interior
    title: OUR INTERIOR
    background: /images/bg-section2.png
    background_alt: sushi
    items: 
        - img: /images/img_interior.png
          alt: sushi
        - img: /images/img_interior.png
          alt: sushi
        - img: /images/img_interior.png
          alt: sushi
        - img: /images/img_interior.png
          alt: sushi
    image_fish: /images/img_fish.png
    image_fish_alt: sushi
    logo_title: /images/logo_title.png
    logo_logo_title_alt: sushi
    circle: /images/circle.svg
    circle_alt: sushi

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      labbel: Id Section
    title:
      type: text
      label: Title
    background:
      type: image
      label: Background
    background_alt:
      type: text
      label: Background Alt
    items[*].img:
      type: image
      label: Item Image
    items[*].alt:
      type: text
      label: Item Image Alt
    image_fish:
      type: image
      label: Image Fish
    image_fish_alt:
      type: text
      label: Image Fish Alt
    logo_title:
      type: image
      label: Logo Title
    logo_logo_title_alt:
      type: text
      label: Logo Title Alt
    circle:
      type: image
      label: Image Circle
    circle_alt:
      type: text
      label: Image Circle Alt



    

