# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Menu Section
  description: Menu Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: menu
    background: /images/bg_menu.png
    logo_title: /images/logo_title.png
    logo_logo_title_alt: sushi
    circle: /images/circle.svg
    circle_alt: sushi
    title_combo: OUR MENU-COMBO
    title_sushi: OUR MENU-SUSHI
    img_combo_left: /images/combo_left.png
    img_combo_left_alt: Sushi
    name_combo_left: Sushi combo 1
    price_combo_left: $45
    img_combo_right: /images/combo_right.png
    img_combo_right_alt: SuShi
    name_combo_right: Sushi combo 2
    price_combo_right: $35
    data_sushi:
        - img: /images/type_sushi.png
          img_alt: Sushi
          title_item: Sushi salmon roll
          content_item: Lorem Ipsum is simply dummy text of the printing and typesetting. 
        - img: /images/type_sushi.png
          img_alt: Sushi
          title_item: Sushi salmon roll
          content_item: Lorem Ipsum is simply dummy text of the printing and typesetting. 
        - img: /images/type_sushi.png
          img_alt: Sushi
          title_item: Sushi salmon roll
          content_item: Lorem Ipsum is simply dummy text of the printing and typesetting. 
        - img: /images/type_sushi.png
          img_alt: Sushi
          title_item: Sushi salmon roll
          content_item: Lorem Ipsum is simply dummy text of the printing and typesetting. 
        - img: /images/type_sushi.png
          img_alt: Sushi
          title_item: Sushi salmon roll
          content_item: Lorem Ipsum is simply dummy text of the printing and typesetting. 
        - img: /images/type_sushi.png
          img_alt: Sushi
          title_item: Sushi salmon roll
          content_item: Lorem Ipsum is simply dummy text of the printing and typesetting. 
    banner_sushi:
        - img: /images/banner_sushi.png
          img_alt: sushi 
        - img: /images/banner_sushi.png
          img_alt: sushi 
        - img: /images/banner_sushi.png
          img_alt: sushi 
        - img: /images/banner_sushi.png
          img_alt: sushi 


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      label: Id Section
    background:
      type: image
      label: Background
    logo_title:
      type: image
      label: Logo Title
    logo_logo_title_alt:
      type: text
      label: Logo Title Alt
    circle:
      type: image
      label: Image Circle
    circle_alt:
      type: text
      label: Image Circle Alt
    title_combo:
      type: text
      label: Title Sushi Combo
    title_sushi:
      type: text
      label: Title Sushi
    img_combo_left:
      type: image
      label: Image Combo Sushi Left
    img_combo_left_alt:
      type: text
      label: Image Combo Sushi Left Alt
    name_combo_left:
      type: text
      label: Name Combo Left
    price_combo_left:
      type: text
      label: Price Combo Left
    img_combo_right:
      type: image
      label: Image Combo Sushi Right
    img_combo_right_alt:
      type: text
      label: Image Combo Sushi Right Alt
    name_combo_right:
      type: text
      label: Name Combo Sushi Right
    price_combo_right:
      type: text
      label: Price Combo Sushi Right
    data_sushi[*].img:
      type: image
      label: Sushi Image
    data_sushi[*].img_alt:
      type: text
      label: Sushi Image Alt
    data_sushi[*].title_item:
      type: text
      label: Title Sushi
    data_sushi[*].content_item:
      type: markdown
      label: Content Sushi
    banner_sushi[*].img:
      type: image
      label: Banner Sushi
    banner_sushi[*].img_alt:
      type: text
      label: Banner Sushi Alt






    

