# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Review Section
  description: Review Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: review
    title: Reviews
    background: images/bg-yellow.png
    alt_image: Beauty Nails
    icon_right: images/icon_left.svg
    icon_left: images/icon_right.svg
    review_items:
      - content: Business coaches are typically experienced entrepreneurs and business owners themselves who decide to use their talents for building and growing a business to help other business owners reach their goals.
        img: images/review_img.png
        alt_img: Beauty Nails
      - content: Business coaches are typically experienced entrepreneurs and business owners themselves who decide to use their talents for building and growing a business to help other business owners reach their goals.
        img: images/review_img.png
        alt_img: Beauty Nails
      - content: Business coaches are typically experienced entrepreneurs and business owners themselves who decide to use their talents for building and growing a business to help other business owners reach their goals.
        img: images/review_img.png
        alt_img: Beauty Nails


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      label: Id Section
    title:
      type: text
      label: Title
    background:
      type: image
      label: Background
    alt_image:
      type: text
      label: Alt Image
    icon_right:
      type: image
      label: Icon Right
    icon_left:
      type: image
      label: Icon Left
    review_items[*].content:
      type: markdown
      label: content
    review_items[*].img:
      type: image
      label: Image
    review_items[*].alt_img:
      type: text
      label: Alt Image


      


    

