# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Service Section
  description: Service Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: service
    title: Our Services
    background: images/bg-white.png
    alt_image: Beauty Nails
    service_items:
        - img: images/pic_service.png
          alt_image: Beauty Nails
          title: MANICURE SERVICES
          content: Duis aute irure dolor in reprehenderit in  velit esse cillum.
        - img: images/pic_service.png
          alt_image: Beauty Nails
          title: MANICURE SERVICES
          content: Duis aute irure dolor in reprehenderit in  velit esse cillum.
        - img: images/pic_service.png
          alt_image: Beauty Nails
          title: MANICURE SERVICES
          content: Duis aute irure dolor in reprehenderit in  velit esse cillum.
        - img: images/pic_service.png
          alt_image: Beauty Nails
          title: MANICURE SERVICES
          content: Duis aute irure dolor in reprehenderit in  velit esse cillum.
    


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text 
      label: Id Section
    title:
      type: text
      label: Title     
    background:
      type: image
      label: Background        
    alt_image:
      type: text
      label: Alt Image     
    service_items[*].img:
      type: image
      label: Image
    service_items[*].alt_image:
      type: text
      label: Alt Image
    service_items[*].title:
      type: text
      label: Title
    service_items[*].content:
      type: markdown
      label: Content



    

