# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Staff Section
  description: Staff Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: staff
    title: Our staffs
    background: images/bg-white.png
    alt_image: Beauty Nails
    staffs_item:
        - square: images/square_staff.png
          alt_image_square: Beauty Nails
          img: images/staff_1.png
          alt_image: Beauty Nails
          circle: images/circle_staff.svg
          alt_image_Circle: Beauty Nails
          author: Adam Jonson
          type: Manicurist
        - square: images/square_staff.png
          alt_image_square: Beauty Nails
          img: images/staff_1.png
          alt_image: Beauty Nails
          circle: images/circle_staff.svg
          alt_image_Circle: Beauty Nails
          author: Adam Jonson
          type: Manicurist
        - square: images/square_staff.png
          alt_image_square: Beauty Nails
          img: images/staff_1.png
          alt_image: Beauty Nails
          circle: images/circle_staff.svg
          alt_image_Circle: Beauty Nails
          author: Adam Jonson
          type: Manicurist


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      label: Id Section
    title:
      type: text
      label: Title
    background:
      type: image
      label:  Background
    alt_image:
      type: text
      label:  Alt Image
    staffs_item[*].square:
      type: image
      label: Image Square
    staffs_item[*].alt_image_square:
      type: text
      label: Alt Image Square
    staffs_item[*].img:
      type: image
      label: Image
    staffs_item[*].alt_image:
      type: text
      label: Alt Image
    staffs_item[*].circle:
      type: image
      label: Image Circle
    staffs_item[*].alt_image_Circle:
      type: text
      label: Alt Image Circle
    staffs_item[*].author:
      type: text
      label: Author
    staffs_item[*].type:
      type: text
      label: Type

        