# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Deal
  description: Home Deal
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: hero

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
    id:
      type: text
      label: Id Section
